"use client";

import {useRef,useState} from "react";
import {AlertCircle,Check,Upload,X} from "lucide-react";

type ImportLPsProps={activeFund:string;existingNames:string[];customCriteria:string[];close:()=>void;save:(rows:any[])=>void};
type ParsedRow={row:number;sheet:string;valid:boolean;reason?:string;lp?:any};
const aliases:Record<string,string[]>={name:["lp name","investor name","institution name","organization name","investor","limited partner","lp"],type:["lp type","investor type","investor category","institution type","organization type","category"],geography:["geography","geographies","hq region","region","location","preferred geography","preferred geographies","geographic focus"],strategy:["strategy","strategies","preferred strategy","preferred strategies","investment strategy","asset class","asset classes","strategy focus"],sector:["sector","sectors","preferred sector","preferred sectors","industry","industries","sector focus","industry focus"],ticket:["ticket size","ticket range","typical ticket","typical ticket size","min max check","check size","commitment size","commitment range"],min:["minimum ticket","min ticket","minimum ticket size","min ticket size","minimum check","min check","minimum commitment"],max:["maximum ticket","max ticket","maximum ticket size","max ticket size","maximum check","max check","maximum commitment"],currency:["currency","ticket currency","reporting currency","commitment currency"],coinvest:["co investment","co-investment","coinvestment","co invest","co-invest"],secondaries:["secondaries","secondaries interest","secondary interest"],owner:["relationship owner","owner","contact owner"],stage:["pipeline stage","stage","status"],next:["next action","next step","follow up"],notes:["notes","previous investments","investment history"]};
const clean=(value:any)=>String(value??"").trim();
const key=(value:any)=>clean(value).toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const ignored=new Set(["preferred","preference","preferences","target","typical","primary","investment","focus","size","range","amount","million","millions","mn","mm","usd","eur","gbp","select","all","applicable"]);
const tokens=(value:any)=>key(value).split(" ").filter(Boolean).map(token=>token.length>3&&token.endsWith("ies")?`${token.slice(0,-3)}y`:token.length>3&&token.endsWith("s")?token.slice(0,-1):token).filter(token=>!ignored.has(token));
const headerScore=(header:string,field:string)=>{const normalized=key(header);if(aliases[field].includes(normalized))return 100;const actual=new Set(tokens(header));return Math.max(0,...aliases[field].map(alias=>{const wanted=tokens(alias);return wanted.length&&wanted.every(token=>actual.has(token))?60+wanted.length:0}))};
const findHeader=(headers:string[],field:string)=>headers.map(header=>({header,score:headerScore(header,field)})).sort((a,b)=>b.score-a.score)[0]?.score?headers.map(header=>({header,score:headerScore(header,field)})).sort((a,b)=>b.score-a.score)[0].header:undefined;
const split=(value:any)=>clean(value).split(/[,;|\/]+/).map(item=>item.trim()).filter(Boolean);
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join("").toUpperCase();
const interestScore=(value:any)=>{const v=key(value);return["yes","high","very high"].includes(v)?100:["selective","medium","maybe"].includes(v)?65:["no","low"].includes(v)?25:60};
const customScore=(value:any)=>{const numeric=Number(value);if(Number.isFinite(numeric)&&clean(value)!=="")return Math.max(0,Math.min(100,numeric));const v=key(value);return v==="very high"?100:v==="high"?90:v==="medium"?60:v==="low"?25:0};
const currencySymbol=(value:any)=>{const v=clean(value).toUpperCase();return v.includes("EUR")||v.includes("€")?"€":v.includes("GBP")||v.includes("£")?"£":v.includes("JPY")||v.includes("¥")?"¥":v.includes("INR")||v.includes("₹")?"₹":v.includes("CAD")?"C$":v.includes("AUD")?"A$":"$"};
const amountsInMillions=(value:any)=>{const matches=[...clean(value).replace(/,/g,"").matchAll(/(\d+(?:\.\d+)?)\s*(bn|billion|b|mm|mn|million|m|k|thousand)?/gi)];return matches.map(match=>{const amount=Number(match[1]),unit=(match[2]||"").toLowerCase();return unit==="bn"||unit==="billion"||unit==="b"?amount*1000:unit==="k"||unit==="thousand"?amount/1000:amount})};

export function mapRows(sheet:string,rawRows:any[][],customCriteria:string[]):ParsedRow[]{
 const headerIndex=rawRows.slice(0,30).map((row,index)=>({index,score:Object.keys(aliases).reduce((sum,field)=>sum+(findHeader(row.map(clean),field)?(field==="name"?5:1):0),0)})).sort((a,b)=>b.score-a.score)[0]?.index??-1;if(headerIndex<0)return[];
 const headers=rawRows[headerIndex].map(clean),nameHeader=findHeader(headers,"name");
 return rawRows.slice(headerIndex+1).map((cells,index)=>{const source=Object.fromEntries(headers.map((header,i)=>[header,cells[i]])),row=headerIndex+index+2,name=clean(nameHeader?source[nameHeader]:"");if(!cells.some(cell=>clean(cell)))return{sheet,row,valid:false,reason:"Blank row"};if(!name)return{sheet,row,valid:false,reason:"LP name is missing"};const get=(field:string)=>{const header=findHeader(headers,field);return header?source[header]:""};const geographies=split(get("geography")),strategies=split(get("strategy")),sectors=split(get("sector")),range=amountsInMillions(get("ticket")),min=amountsInMillions(get("min"))[0]??range[0]??0,max=amountsInMillions(get("max"))[0]??range[1]??range[0]??0,symbol=currencySymbol(get("currency")||get("ticket"));const customScores=Object.fromEntries(customCriteria.map(criterion=>{const label=criterion.replace(/^custom:/,"");const header=headers.find(item=>key(item)===key(label));return[criterion,customScore(header?source[header]:"")]}));return{sheet,row,valid:true,lp:{id:Date.now()+row+Math.floor(Math.random()*100000),name,abbr:initials(name),type:clean(get("type"))||"Institutional Investor",geo:geographies[0]||"Global",geographies:geographies.length?geographies:["Global"],strategies,sectors,ticket:`${symbol}${min||0}–${max||min||0}M`,strategy:strategies.length?85:55,ticketFit:min||max?85:55,geography:geographies.length?85:55,sector:sectors.length?85:55,coInvest:interestScore(get("coinvest")),experience:70,secondaries:interestScore(get("secondaries")),owner:clean(get("owner"))||"Unassigned",stage:clean(get("stage"))||"Potential",next:clean(get("next"))||"Review imported profile",customScores,importNotes:clean(get("notes"))}}}).filter(item=>item.reason!=="Blank row");
}

export function ImportLPs({activeFund,existingNames,customCriteria,close,save}:ImportLPsProps){
 const input=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[rows,setRows]=useState<ParsedRow[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const valid=rows.filter(row=>row.valid&&row.lp),invalid=rows.filter(row=>!row.valid),duplicates=valid.filter(row=>existingNames.some(name=>name.toLowerCase()===row.lp.name.toLowerCase())),ready=valid.filter(row=>!duplicates.includes(row));
 const read=async(selected?:File)=>{const next=selected||input.current?.files?.[0];if(!next)return;setFile(next);setRows([]);setError("");setLoading(true);try{if(next.size>10*1024*1024)throw new Error("Choose a file smaller than 10 MB.");const XLSX=await import("xlsx");const workbook=XLSX.read(await next.arrayBuffer(),{type:"array",cellDates:true});const parsed=workbook.SheetNames.flatMap(sheet=>mapRows(sheet,XLSX.utils.sheet_to_json<any[]>(workbook.Sheets[sheet],{header:1,defval:"",raw:false}),customCriteria));if(!parsed.length)throw new Error("No data rows were found. Include a header row and an LP name column.");setRows(parsed)}catch(reason:any){setError(reason?.message||"We could not read this spreadsheet.")}finally{setLoading(false)}};
 return <div className="overlay"><div className="modal importModal"><div className="panelTop"><div><small>FUND-SPECIFIC WORKSPACE</small><h2>Import LP database</h2><p>Upload Excel or CSV records into {activeFund}. Files are processed in your browser.</p></div><button onClick={close} aria-label="Close import"><X/></button></div><div className="importBody"><input ref={input} type="file" hidden accept=".xlsx,.xls,.csv,text/csv" onChange={event=>read(event.target.files?.[0])}/><button className="uploadDrop" onClick={()=>input.current?.click()}><Upload/><span><b>{file?file.name:"Choose an Excel or CSV file"}</b><small>.xlsx, .xls or .csv · maximum 10 MB · every worksheet is read</small></span></button>{loading&&<p className="importNotice">Reading and mapping spreadsheet columns…</p>}{error&&<p className="importError"><AlertCircle/>{error}</p>}{rows.length>0&&<><div className="importSummary"><span><b>{ready.length}</b> ready</span><span><b>{duplicates.length}</b> duplicates skipped</span><span><b>{invalid.length}</b> rows need attention</span></div><div className="importMapping"><Check/><p><b>Columns mapped automatically</b><span>Recognizes descriptive headings such as Preferred Investment Strategies, Sector Focus and Typical Ticket Size (USD M). Separate multiple values with commas.</span></p></div><div className="importPreview"><table><thead><tr><th>Worksheet / row</th><th>LP</th><th>Geography</th><th>Strategy</th><th>Sector</th><th>Ticket</th><th>Status</th></tr></thead><tbody>{rows.slice(0,50).map((item,index)=><tr key={`${item.sheet}-${item.row}-${index}`}><td>{item.sheet} · {item.row}</td><td>{item.lp?.name||"—"}</td><td>{item.lp?.geographies?.join(", ")||"—"}</td><td>{item.lp?.strategies?.join(", ")||"—"}</td><td>{item.lp?.sectors?.join(", ")||"—"}</td><td>{item.lp?.ticket||"—"}</td><td>{!item.valid?<em className="importBad">{item.reason}</em>:duplicates.includes(item)?<em className="importSkip">Duplicate</em>:<em className="importGood">Ready</em>}</td></tr>)}</tbody></table>{rows.length>50&&<small>Showing the first 50 of {rows.length} rows.</small>}</div></>}</div><footer><button className="light" onClick={close}>Cancel</button><button className="dark" disabled={!ready.length||loading} onClick={()=>save(ready.map(row=>row.lp))}>Import {ready.length||""} LP{ready.length===1?"":"s"}</button></footer></div></div>;
}
