"use client";

import {useRef,useState} from "react";
import {AlertCircle,Check,Upload,X} from "lucide-react";
import {mapRows} from "./lp-import-core";

type ImportLPsProps={activeFund:string;existingNames:string[];customCriteria:string[];close:()=>void;save:(rows:any[])=>void};
type ParsedRow={row:number;sheet:string;valid:boolean;reason?:string;lp?:any};

export function ImportLPs({activeFund,existingNames,customCriteria,close,save}:ImportLPsProps){
 const input=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[rows,setRows]=useState<ParsedRow[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 const valid=rows.filter(row=>row.valid&&row.lp),invalid=rows.filter(row=>!row.valid),duplicates=valid.filter(row=>existingNames.some(name=>name.toLowerCase()===row.lp.name.toLowerCase())),ready=valid.filter(row=>!duplicates.includes(row));
 const read=async(selected?:File)=>{const next=selected||input.current?.files?.[0];if(!next)return;setFile(next);setRows([]);setError("");setLoading(true);try{if(next.size>10*1024*1024)throw new Error("Choose a file smaller than 10 MB.");const XLSX=await import("xlsx");const workbook=XLSX.read(await next.arrayBuffer(),{type:"array",cellDates:true});const parsed=workbook.SheetNames.flatMap(sheet=>mapRows(sheet,XLSX.utils.sheet_to_json<any[]>(workbook.Sheets[sheet],{header:1,defval:"",raw:false}),customCriteria));if(!parsed.length)throw new Error("No data rows were found. Include a header row and an LP name column.");setRows(parsed)}catch(reason:any){setError(reason?.message||"We could not read this spreadsheet.")}finally{setLoading(false)}};
 return <div className="overlay"><div className="modal importModal"><div className="panelTop"><div><small>FUND-SPECIFIC WORKSPACE</small><h2>Import LP database</h2><p>Upload Excel or CSV records into {activeFund}. Files are processed in your browser.</p></div><button onClick={close} aria-label="Close import"><X/></button></div><div className="importBody"><input ref={input} type="file" hidden accept=".xlsx,.xls,.csv,text/csv" onChange={event=>read(event.target.files?.[0])}/><button className="uploadDrop" onClick={()=>input.current?.click()}><Upload/><span><b>{file?file.name:"Choose an Excel or CSV file"}</b><small>.xlsx, .xls or .csv · maximum 10 MB · every worksheet is read</small></span></button>{loading&&<p className="importNotice">Reading and mapping spreadsheet columns…</p>}{error&&<p className="importError"><AlertCircle/>{error}</p>}{rows.length>0&&<><div className="importSummary"><span><b>{ready.length}</b> ready</span><span><b>{duplicates.length}</b> duplicates skipped</span><span><b>{invalid.length}</b> rows need attention</span></div><div className="importMapping"><Check/><p><b>Columns mapped automatically</b><span>Recognizes descriptive headings such as Preferred Investment Strategies, Sector Focus and Typical Ticket Size (USD M). Separate multiple values with commas.</span></p></div><div className="importPreview"><table><thead><tr><th>Worksheet / row</th><th>LP</th><th>Geography</th><th>Strategy</th><th>Sector</th><th>Ticket</th><th>Status</th></tr></thead><tbody>{rows.slice(0,50).map((item,index)=><tr key={`${item.sheet}-${item.row}-${index}`}><td>{item.sheet} · {item.row}</td><td>{item.lp?.name||"—"}</td><td>{item.lp?.geographies?.join(", ")||"—"}</td><td>{item.lp?.strategies?.join(", ")||"—"}</td><td>{item.lp?.sectors?.join(", ")||"—"}</td><td>{item.lp?.ticket||"—"}</td><td>{!item.valid?<em className="importBad">{item.reason}</em>:duplicates.includes(item)?<em className="importSkip">Duplicate</em>:<em className="importGood">Ready</em>}</td></tr>)}</tbody></table>{rows.length>50&&<small>Showing the first 50 of {rows.length} rows.</small>}</div></>}</div><footer><button className="light" onClick={close}>Cancel</button><button className="dark" disabled={!ready.length||loading} onClick={()=>save(ready.map(row=>row.lp))}>Import {ready.length||""} LP{ready.length===1?"":"s"}</button></footer></div></div>;
}
