"use client";
import {useMemo,useState} from "react";
import {Search,SlidersHorizontal,Upload,Plus,ChevronDown,ArrowUpRight,Building2,Target,Settings2,LayoutDashboard,KanbanSquare,Database,BriefcaseBusiness,Sparkles,X,Check,CircleAlert,FileSpreadsheet} from "lucide-react";
type LP={id:number;name:string;abbr:string;type:string;geo:string;ticket:string;strategy:number;ticketFit:number;geography:number;sector:number;coInvest:number;experience:number;secondaries:number;owner:string;stage:string;next:string};
const lps:LP[]=[
{id:1,name:"Asterion Public Pension",abbr:"AP",type:"Public Pension",geo:"Europe",ticket:"$40–75M",strategy:96,ticketFit:92,geography:94,sector:88,coInvest:100,experience:84,secondaries:90,owner:"Maya Chen",stage:"Meeting",next:"Send data room access"},
{id:2,name:"Sovereign Partners Authority",abbr:"SP",type:"Sovereign Wealth",geo:"Middle East",ticket:"$75–150M",strategy:94,ticketFit:86,geography:82,sector:93,coInvest:100,experience:90,secondaries:78,owner:"James Okafor",stage:"Due Diligence",next:"Answer ESG questionnaire"},
{id:3,name:"Meridian University Endowment",abbr:"MU",type:"Endowment",geo:"North America",ticket:"$20–40M",strategy:91,ticketFit:96,geography:78,sector:86,coInvest:82,experience:76,secondaries:72,owner:"Maya Chen",stage:"Contacted",next:"Schedule investment team call"},
{id:4,name:"Harbor Family Office",abbr:"HF",type:"Family Office",geo:"Europe",ticket:"$10–25M",strategy:86,ticketFit:78,geography:96,sector:90,coInvest:94,experience:72,secondaries:68,owner:"Priya Shah",stage:"Potential",next:"Warm intro via ALN"},
{id:5,name:"Nordic Insurance Group",abbr:"NI",type:"Insurance",geo:"Europe",ticket:"$25–50M",strategy:80,ticketFit:90,geography:92,sector:68,coInvest:60,experience:84,secondaries:82,owner:"James Okafor",stage:"Soft Circled",next:"Confirm allocation range"},
{id:6,name:"Cedar Grove Foundation",abbr:"CG",type:"Foundation",geo:"North America",ticket:"$10–30M",strategy:76,ticketFit:82,geography:70,sector:82,coInvest:55,experience:68,secondaries:60,owner:"Priya Shah",stage:"Passed",next:"Revisit next vintage"},
{id:7,name:"Pacific FoF Partners",abbr:"PF",type:"Fund of Funds",geo:"Asia Pacific",ticket:"$15–35M",strategy:82,ticketFit:84,geography:58,sector:74,coInvest:72,experience:90,secondaries:88,owner:"Maya Chen",stage:"Potential",next:"Share one-page overview"}];
const base={strategy:25,ticketFit:20,geography:15,sector:15,coInvest:10,experience:10,secondaries:5};
const names:any={strategy:"Strategy",ticketFit:"Ticket size",geography:"Geography",sector:"Sector",coInvest:"Co-investment",experience:"Manager experience",secondaries:"Secondaries"};
export default function Home(){const[view,setView]=useState("Dashboard"),[weights,setWeights]=useState(base),[chosen,setChosen]=useState<LP|null>(null),[query,setQuery]=useState(""),[geo,setGeo]=useState("All geographies"),[priority,setPriority]=useState("All priorities"),[panel,setPanel]=useState(""),[toast,setToast]=useState("");
 const score=(lp:LP)=>Math.round((Object.keys(weights) as (keyof typeof weights)[]).reduce((n,k)=>n+lp[k]*weights[k],0)/Object.values(weights).reduce((a,b)=>a+b));
 const rows=useMemo(()=>lps.map(x=>({...x,score:score(x)})).filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&(geo==="All geographies"||x.geo===geo)&&(priority==="All priorities"||(priority==="High potential"&&x.score>=80)||(priority==="Medium potential"&&x.score>=60&&x.score<80))).sort((a,b)=>b.score-a.score),[weights,query,geo,priority]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),1800)};
 return <div className="shell"><aside className="side"><div className="brand"><b>N</b><div><strong>Northstar</strong><small>LP Intelligence</small></div></div><div className="fund"><small>Active fund</small><strong>Northstar Fund III</strong><ChevronDown/></div><nav>{[[LayoutDashboard,"Dashboard"],[Target,"LP Matches"],[KanbanSquare,"Pipeline"],[Database,"LP Database"],[BriefcaseBusiness,"Funds"]].map(([I,n]:any)=><button className={view===n?"on":""} onClick={()=>setView(n)} key={n}><I/>{n}</button>)}</nav><div className="account"><button><Settings2/>Settings</button><p><i>MC</i><span><b>Maya Chen</b><small>Atlas Ridge Partners</small></span></p></div></aside>
 <main><header><div><small>FUNDRAISING WORKSPACE</small><h1>{view==="Pipeline"?"Fundraising pipeline":view==="LP Database"?"LP database":"Northstar Fund III"}</h1></div><div><button className="light" onClick={()=>setPanel("import")}><Upload/>Import LPs</button><button className="dark" onClick={()=>notify("New LP workspace opened")}><Plus/>Add LP</button></div></header>
 {view==="Pipeline"?<Pipeline/>:view==="LP Database"?<Cards choose={setChosen}/>:<><section className="stats"><article className="total"><span>LP universe</span><b>1,250</b><small>Across 26 markets</small></article><Stat c="green" title="High potential" n="85" note="14 newly identified"/><Stat c="gold" title="Medium potential" n="210" note="32 need review"/><Stat c="gray" title="Low / no potential" n="955" note="Review as capacity allows"/></section>
 <section className="insight"><Sparkles/><p><b>Fund III has 14 newly identified high-potential LPs</b><span>Strategy and ticket size are driving the strongest matches. 6 prospects also have an existing relationship with your team.</span></p><button onClick={()=>setPriority("High potential")}>View prospects <ArrowUpRight/></button></section>
 <section className="board"><div className="board-title"><div><h2>LP compatibility</h2><p>Ranked against your current fund profile and scoring model.</p></div><button onClick={()=>setPanel("weights")}><SlidersHorizontal/>Scoring model <b>{Object.values(weights).reduce((a,b)=>a+b)}%</b></button></div><div className="filters"><label><Search/><input placeholder="Search LPs" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={geo} onChange={e=>setGeo(e.target.value)}><option>All geographies</option><option>Europe</option><option>North America</option><option>Middle East</option><option>Asia Pacific</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option>All priorities</option><option>High potential</option><option>Medium potential</option></select><span>{rows.length} results</span></div><div className="table"><table><thead><tr><th>LP</th><th>Score</th><th>Ticket fit</th><th>Strategy</th><th>Geography</th><th>Co-invest</th><th>Stage</th><th>Owner</th><th/></tr></thead><tbody>{rows.map(x=><tr onClick={()=>setChosen(x)} key={x.id}><td><LPCell lp={x}/></td><td><strong className={x.score>=80?"score good":"score"}>{x.score}<small>/100</small></strong></td><td><Fit n={x.ticketFit}/></td><td><Fit n={x.strategy}/></td><td><Fit n={x.geography}/></td><td>{x.coInvest>=80?<em className="yes"><Check/>Yes</em>:"Selective"}</td><td><em className="stage">{x.stage}</em></td><td>{x.owner}</td><td><ArrowUpRight/></td></tr>)}</tbody></table></div></section></>}
 </main>{panel==="weights"&&<Weights w={weights} setW={setWeights} close={()=>setPanel("")} notify={notify}/>} {panel==="import"&&<Import close={()=>setPanel("")} notify={notify}/>} {chosen&&<Profile lp={chosen} score={score(chosen)} w={weights} close={()=>setChosen(null)} notify={notify}/>} {toast&&<div className="toast"><Check/>{toast}</div>}</div>}
function Stat({c,title,n,note}:any){return <article className="stat"><i className={c}/><span>{title}</span><b>{n}</b><small>{note}</small></article>}; function LPCell({lp}:any){return <div className="lp"><i className={`logo l${lp.id}`}>{lp.abbr}</i><p><b>{lp.name}</b><small>{lp.type} · {lp.geo}</small></p></div>}; function Fit({n}:any){return <span className={`fit ${n>=85?"hi":n>=70?"mid":"lo"}`}><i/>{n>=85?"High":n>=70?"Medium":"Low"}</span>}
function Weights({w,setW,close,notify}:any){return <Overlay><aside className="drawer"><Top title="Scoring weights" sub="Choose what matters most for Fund III. Scores update instantly." close={close}/><div className="weightTotal"><span>Total allocation</span><b>{Object.values(w).reduce((a:any,b:any)=>a+b,0) as number}%</b></div><div className="weights">{Object.keys(w).map(k=><label key={k}><span>{names[k]}<b>{w[k]}%</b></span><input type="range" min="0" max="40" value={w[k]} onChange={e=>setW({...w,[k]:+e.target.value})}/><small>Contribution to the compatibility score</small></label>)}</div><footer><button className="light" onClick={()=>setW(base)}>Reset</button><button className="dark" onClick={()=>{close();notify("Scoring model saved")}}>Save model</button></footer></aside></Overlay>}
function Profile({lp,score,w,close,notify}:any){return <Overlay><aside className="drawer profile"><Top title={lp.name} sub={`${lp.type} · ${lp.geo} · Typical ticket ${lp.ticket}`} close={close}/><div className="profileScore"><strong>{score}<small>/100</small></strong><p><b>{score>=80?"High potential":"Medium potential"}</b><span>Strong fit for Northstar Fund III</span></p></div><div className="profileBtns"><button className="dark" onClick={()=>notify("Moved to Contacted")}>Move to Contacted</button><button className="light">Add note</button></div><Block title="Why this LP is a strong match"><ul className="reasons"><li><Check/>Invests consistently in European middle-market buyout</li><li><Check/>Target commitment fits the LP’s normal {lp.ticket} range</li><li><Check/>Has participated in co-investments across prior funds</li></ul></Block><Block title="Potential gaps"><ul className="gaps"><li><CircleAlert/>Fund size is near the upper end of the LP’s typical range</li><li><CircleAlert/>Limited historical exposure to specialist healthcare services</li></ul></Block><Block title="Score breakdown"><div className="breakdown">{Object.keys(w).map(k=><div key={k}><span>{names[k]}<small>{w[k]}% weight</small></span><i><b style={{width:`${lp[k]}%`}}/></i><strong>{lp[k]}%</strong></div>)}</div></Block><Block title="Recent fund investments">{["Northbridge Buyout VII","Talon Healthcare Partners IV","Crown European Capital V"].map((x,i)=><div className="history" key={x}><Building2/><p><b>{x}</b><span>{2025-i} · ${i?35:50}M commitment</span></p></div>)}</Block></aside></Overlay>}
function Import({close,notify}:any){return <Overlay><div className="modal"><Top title="Map your LP file" sub="Review the detected columns before importing 248 prospects." close={close}/><div className="file"><FileSpreadsheet/><p><b>European_LP_Prospects.xlsx</b><span>248 rows · 8 columns</span></p><Check/></div><div className="mapping">{[["Investor Name","LP name"],["Investor Category","LP type"],["HQ Region","Geography"],["Min / Max Check","Ticket size"],["Preferred Strategy","Preferred strategies"]].map(x=><label key={x[0]}><b>{x[0]}</b><ArrowUpRight/><select defaultValue={x[1]}><option>{x[1]}</option><option>Do not import</option></select><Check/></label>)}</div><footer><button className="light" onClick={close}>Cancel</button><button className="dark" onClick={()=>{close();notify("248 LPs imported successfully")}}>Import 248 LPs</button></footer></div></Overlay>}
function Top({title,sub,close}:any){return <div className="panelTop"><div><small>FUND-SPECIFIC WORKSPACE</small><h2>{title}</h2><p>{sub}</p></div><button onClick={close}><X/></button></div>};function Overlay({children}:any){return <div className="overlay">{children}</div>};function Block({title,children}:any){return <section className="block"><h3>{title}</h3>{children}</section>}
function Pipeline(){const stages=["Potential","Contacted","Meeting","Due Diligence","Soft Circled","Committed"];return <section className="pipeline"><div className="pipelineTop"><div><p>Northstar Fund III · 47 active prospects</p><h2>$485M weighted pipeline</h2></div></div><div className="kanban">{stages.map((s,i)=><div className="column" key={s}><h3>{s}<b>{lps.filter(x=>x.stage===s).length||[18,11,7,5,4,2][i]}</b></h3>{lps.filter(x=>x.stage===s).map(lp=><article key={lp.id}><LPCell lp={lp}/><p>Next: {lp.next}</p><footer><span>{lp.owner}</span><small>Sep {14+i}</small></footer></article>)}</div>)}</div></section>}
function Cards({choose}:any){return <section className="board database"><div className="board-title"><div><h2>1,250 LP profiles</h2><p>Institutional investors with preferences and relationship history.</p></div><button className="dark"><Plus/>Add LP</button></div><div className="cards">{lps.map(lp=><article onClick={()=>choose(lp)} key={lp.id}><LPCell lp={lp}/><h3>{lp.ticket}</h3><p>{lp.strategy>=90?"Buyout · Healthcare · Co-invest":"Growth · Private Equity · Secondaries"}</p><footer><span>Owner: {lp.owner}</span><ArrowUpRight/></footer></article>)}</div></section>}
