"use client";
import {useState} from "react";
import {Building2,Plus,Pencil,X,BriefcaseBusiness} from "lucide-react";
import "./gp-funds.css";

export function GPFunds({gps,activeGP,selectGP,funds,fundOwner,activeFund,selectFund,addGP,addFund,editFund,updateGP}:any){
 const[editing,setEditing]=useState<string|null>(null);
 return <><section className="workspacePage"><div className="workspaceHero"><div><small>MANAGER WORKSPACE</small><h2>GPs & funds</h2><p>Each GP keeps its own funds, LP database, pipeline, and matching activity together.</p></div><button className="dark" onClick={addGP}><Plus/>Add GP</button></div><div className="gpStack">{gps.map((gp:string)=>{const gpFunds=funds.filter((fund:string)=>fundOwner[fund]===gp);return <article className={`workspaceCard gpWorkspace ${activeGP===gp?"active":""}`} key={gp}><div className="gpWorkspaceHead" role="button" tabIndex={0} onClick={()=>selectGP(gp)} onKeyDown={e=>(e.key==="Enter"||e.key===" ")&&selectGP(gp)}><div><i>{gp.split(" ").map(x=>x[0]).join("").slice(0,2)}</i><span><small>GENERAL PARTNER</small><b>{gp}</b><em>{gpFunds.length} {gpFunds.length===1?"fund":"funds"}</em></span></div><div>{activeGP===gp&&<strong>Active GP</strong>}<button aria-label={`Edit ${gp}`} onClick={e=>{e.stopPropagation();setEditing(gp)}}><Pencil/></button></div></div><div className="gpFundList"><div className="gpFundListHead"><span>Fund mandates</span><button className="light" onClick={()=>addFund(gp)}><Plus/>Add fund</button></div>{gpFunds.length===0?<p className="gpEmpty">No funds yet. Add the first fund for this GP.</p>:gpFunds.map((fund:string,index:number)=><button className={`gpFundRow ${fund===activeFund?"active":""}`} onClick={()=>selectFund(fund)} key={fund}><i>F{index+1}</i><span><b>{fund}</b><small>{fund===activeFund?"Active fundraising workspace":"Open fund workspace"}</small></span>{fund===activeFund&&<em>Active</em>}<span className="fundEdit" role="button" aria-label={`Edit ${fund}`} onClick={e=>{e.stopPropagation();editFund(fund)}}><Pencil/></span></button>)}</div></article>})}</div></section>{editing&&<EditGP name={editing} close={()=>setEditing(null)} save={(newName:string)=>{updateGP(editing,newName);setEditing(null)}}/>}</>
}

function EditGP({name,close,save}:any){const[value,setValue]=useState(name);return <div className="overlay"><div className="modal gpModal"><div className="panelTop"><div><small>GENERAL PARTNER PROFILE</small><h2>Edit {name}</h2><p>Maintain the manager context used across funds and LP conversations.</p></div><button onClick={close}><X/></button></div><div className="formSection"><h3>Firm profile & preferences</h3><div className="formGrid"><label className="wide"><span>GP / firm name</span><input value={value} onChange={e=>setValue(e.target.value)}/></label><label><span>Headquarters</span><input defaultValue="London, United Kingdom"/></label><label><span>Website</span><input defaultValue="https://atlasridge.com"/></label><label><span>Primary strategy</span><select defaultValue="Private Equity"><option>Private Equity</option><option>Venture Capital</option><option>Private Credit</option><option>Infrastructure</option><option>Real Estate</option></select></label><label><span>Assets under management</span><input defaultValue="$2.5B"/></label><label><span>Target geographies</span><input defaultValue="Europe, North America"/></label><label><span>Preferred sectors</span><input defaultValue="Healthcare, Business Services, Technology"/></label><label><span>Primary fundraising contact</span><input defaultValue="Maya Chen"/></label><label><span>Contact email</span><input defaultValue="maya@atlasridge.com"/></label><label className="wide"><span>Manager track record & notes</span><textarea defaultValue="Established middle-market manager with three prior institutional vintages."/></label></div></div><footer><button className="light" onClick={close}>Cancel</button><button className="dark" disabled={!value.trim()} onClick={()=>save(value.trim())}>Save GP profile</button></footer></div></div>}

export function AddGP({close,save}:any){const[name,setName]=useState(""),[fund,setFund]=useState(""),[email,setEmail]=useState("");return <div className="overlay"><div className="modal gpModal"><div className="panelTop"><div><small>MANAGER WORKSPACE</small><h2>Add GP</h2><p>Create the firm that will own fund mandates and fundraising activity.</p></div><button onClick={close}><X/></button></div><div className="formSection"><h3>Firm profile</h3><div className="formGrid"><label className="wide"><span>GP / firm name *</span><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Atlas Ridge Partners"/></label><label className="wide"><span>Initial fund name *</span><input value={fund} onChange={e=>setFund(e.target.value)} placeholder="e.g. Atlas Ridge Fund I"/></label><label><span>Headquarters</span><input placeholder="London, United Kingdom"/></label><label><span>Website</span><input placeholder="https://"/></label><label><span>Primary contact</span><input placeholder="Full name"/></label><label><span>Contact email</span><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@firm.com"/></label><label><span>Firm strategy</span><select><option>Private Equity</option><option>Venture Capital</option><option>Private Credit</option><option>Real Assets</option></select></label><label><span>Assets under management</span><input placeholder="e.g. $2.5B"/></label><label className="wide"><span>Firm description</span><textarea placeholder="Investment focus, track record, and differentiators"/></label></div></div><footer><button className="light" onClick={close}>Cancel</button><button className="dark" disabled={!name.trim()||!fund.trim()} onClick={()=>save(name.trim(),fund.trim())}>Create GP</button></footer></div></div>}
